version: 1.0

build:
  name: "Path Blocker Online - iOS Build"
  environments:
    - xcode: latest
  preBuildScripts:
    - name: "📦 Pre-Build: Install CocoaPods"
      script: |
        echo "🚀 Starting CocoaPods installation..."
        cd ios
        if [ -f "Podfile" ]; then
          echo "✅ Podfile found. Installing dependencies..."
          pod repo update
          pod install
        else
          echo "❌ Podfile not found in ios/. Build will fail without CocoaPods dependencies."
          exit 1
        fi
        echo "✅ Pods installed successfully."
  postBuildScripts:
    - name: "✅ Post-Build Complete"
      script: |
        echo "🎉 Build and pod installation completed successfully!"
